export type OptionType = { label: string; value: string };
export const columnsMapOPMs: {
  [key: string]: string;
} = {
  'value': 'value', // Exemplo: 'Ord' mapeia para 'id'
  'OPM': 'label',
};
export enum OPMs {
  CoordenadoriaGeraldeOperaçoes = "cgo",
  ComandoDePoliciamentoDaCapital = "1ºCRPM",
  ComandoDePoliciamentoMetropolitano = "2ºCRPM",
  ComandoDePoliciamentoDoInteriorNorte = "3ºCRPM",
  ComandoDePoliciamentoDoInteriorSul = "4ºCRPM",
  ComandoDePoliciamentoEspecializado = "cpe",
  BatalhaoDePoliciaDeTransitoUrbanoERodoviarioEstadual = "bpre",
  BatalhaoDePoliciamentoTuristico = "bptur",
  BatalhaoDePoliciaDeMeioAmbiente = "bpma",
  RegimentoDePoliciaMontada = "rpmont",
  BatalhaoDePoliciamentoDeGuardaExternaDosPresidios = "bpgep",
  ComandoDePoliciamentoDeChoque = "cpchoque",
  BatalhaoDeComandoTaticoMotorizado = "cotam",
  BatalhaoDeOperacoesPoliciaisEspeciais = "bope",
  BatalhaoEspecializadoEmPoliciamentoDoInterior = "bepi",
  BatalhaoDePoliciaDeChoque = "bpchoque",
  ComandoDePrevencaoEApoioAsComunidades = "copac",
  ComandoDePoliciamentoDeRondasDeAcoesIntensivasEOstensivas = "cpraio",
  PrimeiroBPM = "1bpm",
  SegundoBPM = "2bpm",
  TerceiroBPM = "3bpm",
  QuartoBPM = "4bpm",
  QuintoBPM = "5bpm",
  SextoBPM = "6bpm",
  SetimoBPM = "7bpm",
  OitavoBPM = "8bpm",
  NonoBPM = "9bpm",
  DecimoBPM = "10bpm",
  DecimoPrimeiroBPM = "11bpm",
  DecimoSegundoBPM = "12bpm",
  DecimoTerceiroBPM = "13bpm",
  DecimoQuartoBPM = "14bpm",
  DecimoQuintoBPM = "15bpm",
  DecimoSextoBPM = "16bpm",
  DecimoSetimoBPM = "17bpm",
  DecimoOitavoBPM = "18bpm",
  DecimoNonoBPM = "19bpm",
  VigesimoBPM = "20bpm",
  VigesimoPrimeiroBPM = "21bpm",
  VigesimoSegundoBPM = "22bpm",
  VigesimoTerceiroBPM = "23bpm",
  VigesimoQuartoBPM = "24bpm",
  VigesimoQuintoBPM = "25bpm",
  BatalhaoDeSegurancaPatrimonial = "bsp",
  PrimeiraCPG = "1cpg",
  SegundaCPG = "2cpg",
  TerceiraCPG = "3cpg",
  DPGI = "dpgi",
  CETIC = "cetic",
  CODIP = "codip",
  COLOG = "colog",
  COAFI = "coafi",
  CGP = "cgp",
  CPMCE = "cpmce",
  CSAS = "csas",
  COGEPRO = "cogepro",
  COGEI = "cogei",
  CPRAIO = "cpraio",
  PrimeiroBPRAIO = "1bpraio",
  SegundoBPRAIO = "2bpraio",
  TerceiroBPRAIO = "3bpraio",
  QuartoBPRAIO = "4bpraio",
  QuintoBPRAIO = "5bpraio",
}


export const optionsOPMs: OptionType[] = [
  { label: 'Coordenadoria Geral de Operações – CGO', value: "cgo" },
  { label: 'Comando de Policiamento da Capital – 1º CRPM', value: "1ºCRPM" },
  { label: 'Comando de Policiamento Metropolitano – 2º CRPM', value: "2ºCRPM" },
  { label: 'Comando de Policiamento do Interior Norte – 3º CRPM', value: "3ºCRPM" },
  { label: 'Comando de Policiamento do Interior Sul – 4º CRPM', value: "4ºCRPM" },
  { label: 'Comando de Policiamento Especializado – CPE', value: "cpe" },
  { label: 'Batalhão de Polícia de Trânsito Urbano e Rodoviário Estadual – BPRE', value: "bpre" },
  { label: 'Batalhão de Policiamento Turístico – BPTUR', value: "bptur" },
  { label: 'Batalhão de Polícia de Meio Ambiente – BPMA', value: "bpma" },
  { label: 'Regimento de Polícia Montada – RPMONT', value: "rpmont" },
  { label: 'Batalhão de Policiamento de Guarda Externa dos Presídios – BPGEP', value: "bpgep" },
  { label: 'Comando de Policiamento de Choque – CPCHOQUE', value: "cpchoque" },
  { label: 'Batalhão de Comando Tático Motorizado – COTAM', value: "cotam" },
  { label: 'Batalhão de Operações Policiais Especiais – BOPE', value: "bope" },
  { label: 'Batalhão Especializado em Policiamento do Interior – BEPI', value: "bepi" },
  { label: 'Batalhão de Polícia de Choque – BPCHOQUE', value: "bpchoque" },
  { label: 'Comando de Prevenção e Apoio às Comunidades – COPAC', value: "copac" },

  { label: '1º BPM (Russas)', value: "1bpm" },
  { label: '2º BPM (Juazeiro do Norte)', value: "2bpm" },
  { label: '3º BPM (Sobral)', value: "3bpm" },
  { label: '4º BPM (Canindé)', value: "4bpm" },
  { label: '5º BPM (Centro – Fortaleza)', value: "5bpm" },
  { label: '6º BPM (Parangaba – Fortaleza)', value: "6bpm" },
  { label: '7º BPM (Crateús)', value: "7bpm" },
  { label: '8º BPM (Aldeota – Fortaleza)', value: "8bpm" },
  { label: '9º BPM (Quixadá)', value: "9bpm" },
  { label: '10º BPM (Iguatu)', value: "10bpm" },
  { label: '11º BPM (Itapipoca)', value: "11bpm" },
  { label: '12º BPM (Caucaia)', value: "12bpm" },
  { label: '13º BPM (Tauá)', value: "13bpm" },
  { label: '14º BPM (Maracanaú)', value: "14bpm" },
  { label: '15º BPM (Eusébio)', value: "15bpm" },
  { label: '16º BPM (Messejana – Fortaleza)', value: "16bpm" },
  { label: '17º BPM (Conjunto Ceará – Fortaleza)', value: "17bpm" },
  { label: '18º BPM (Antônio Bezerra – Fortaleza)', value: "18bpm" },
  { label: '19º BPM (Tancredo Neves – Fortaleza)', value: "19bpm" },
  { label: '20º BPM (Cristo Redentor – Fortaleza)', value: "20bpm" },
  { label: '21º BPM (Cj. Esperança – Fortaleza)', value: '21bpm' },
  { label: '22º BPM (Papicu – Fortaleza)', value: '22bpm' },
  { label: '23º BPM (Paracuru)', value: '23bpm' },
  { label: '24º BPM (Maranguape)', value: '24bpm' },
  { label: '25º BPM (Horizonte)', value: '25bpm' },
  { label: 'Batalhão de Segurança Patrimonial – BSP', value: "bsp" },
  { label: '1ª Companhia de Policiamento de Guarda – 1ª CPG', value: "1cpg" },
  { label: '2ª Companhia de Policiamento de Guarda – 2ª CPG', value: "2cpg" },
  { label: '3ª Companhia de Policiamento de Guarda – 3ª CPG', value: "3cpg" },
  { label: 'DPGI - (Departamento de Polícia de Gestão Interna)', value: 'dpgi' },
  { label: 'CETIC - (Centro de Tecnologia da Informação e Comunicação)', value: 'cetic' },
  { label: 'CODIP - (Coordenadoria de Inteligência Policial)', value: 'codip' },
  { label: 'COLOG - (Coordenadoria de Logística)', value: 'colog' },
  { label: 'COAFI - (Coordenadoria de Assuntos Financeiros e Infraestrutura)', value: 'coafi' },
  { label: 'CGP - (Coordenação de Gestão de Pessoas)', value: 'cgp' },
  { label: 'CPMCE - (Comando de Policiamento do Meio-Centro Este)', value: 'cpmce' },
  { label: 'CSAS - (Coordenadoria de Segurança e Assuntos Sociais)', value: 'csas' },
  { label: 'COGEPRO - (Coordenadoria de Gestão e Processos)', value: 'cogepro' },
  { label: 'COGEI - (Coordenadoria de Gestão de Estatísticas e Informações)', value: 'cogei' },
  { label: 'CPRAIO - (Comando de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: 'cpraio' },
  { label: '1º BPRAIO - (1º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '1bpraio' },
  { label: '2º BPRAIO - (2º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '2bpraio' },
  { label: '3º BPRAIO - (3º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '3bpraio' },
  { label: '4º BPRAIO - (4º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '4bpraio' },
  { label: '5º BPRAIO - (5º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '5bpraio' },

  { label: '1ª CIPM (Morada Nova)', value: '1cipm' },
  { label: '2ª CIPM (Catunda)', value: '2cipm' },
  { label: '3ª CIPM (Amontada)', value: '3cipm' },
  { label: '4ª CIPM (Santa Quitéria)', value: '4cipm' },
  { label: '5ª CIPM (Nova Russas)', value: '5cipm' },
];


export const options1CRPM: OptionType[] =

  [
    // ... outras opções
    { label: '5º BPM (Centro – Fortaleza)', value: '5bpm' },
    { label: '6º BPM (Parangaba – Fortaleza)', value: '6bpm' },
    { label: '8º BPM (Aldeota – Fortaleza)', value: '8bpm' },
    { label: '16º BPM (Messejana – Fortaleza)', value: "16bpm" },
    { label: '17º BPM (Conjunto Ceará – Fortaleza)', value: "17bpm" },
    { label: '18º BPM (Antônio Bezerra – Fortaleza)', value: "18bpm" },
    { label: '19º BPM (Tancredo Neves – Fortaleza)', value: "19bpm" },
    { label: '20º BPM (Cristo Redentor – Fortaleza)', value: '20bpm' },
    { label: '21º BPM (Cj. Esperança – Fortaleza)', value: '21bpm' },
    { label: '22º BPM (Papicu – Fortaleza)', value: '22bpm' },
  ];

export const options2CRPM: OptionType[] = [
  // ... outras opções
  { label: '14º BPM (Maracanaú)', value: '14bpm' },
  { label: '15º BPM (Eusébio)', value: '15bpm' },
  { label: '23º BPM (Paracuru)', value: '23bpm' },
  { label: '24º BPM (Maranguape)', value: '24bpm' },
  { label: '25º BPM (Horizonte)', value: '25bpm' },
];
export const options3CRPM: OptionType[] = [
  // ... outras opções
  { label: '3º BPM (Sobral)', value: '3bpm' },
  { label: '4º BPM (Canindé)', value: '4bpm' },
  { label: '7º BPM (Crateús)', value: '7bpm' },
  { label: '11º BPM (Itapipoca)', value: '11bpm' },
  { label: '1ª CIPM (Morada Nova)', value: '1cipm' },
  { label: '2ª CIPM (Catunda)', value: '2cipm' },
  { label: '3ª CIPM (Amontada)', value: '3cipm' },
];
export const options4CRPM: OptionType[] = [

  { label: '1º BPM (Russas)', value: '1bpm' },
  { label: '2º BPM (Juazeiro do Norte)', value: '2bpm' },
  { label: '9º BPM (Quixadá)', value: '9bpm' },
  { label: '10º BPM (Iguatú)', value: '10bpm' },
  { label: '13º BPM (Tauá)', value: '13bpm' },
  { label: '4ª CIPM (Santa Quitéria)', value: '4cipm' },
  { label: '5ª CIPM (Nova Russas)', value: '5cipm' },
];
export const optionsCPCHOQUE: OptionType[] = [
  { label: 'Batalhão de Policiamento de Guarda Externa dos Presídios – BPGEP', value: 'bpgep' },
  { label: 'Comando de Policiamento de Choque – CPCHOQUE', value: 'cpchoque' },
  { label: 'Batalhão de Comando Tático Motorizado – COTAM', value: 'cotam' },
  { label: 'Batalhão de Operações Policiais Especiais – BOPE', value: 'bope' },
  { label: 'Batalhão Especializado em Policiamento do Interior – BEPI', value: 'bepi' },
  { label: 'Batalhão de Polícia de Choque – BPCHOQUE', value: 'bpchoque' },
];

export const optionsCPE: OptionType[] = [
  { label: 'Batalhão de Polícia de Trânsito Urbano e Rodoviário Estadual – BPRE', value: 'bpre' },
  { label: 'Batalhão de Policiamento Turístico – BPTUR', value: 'bptur' },
  { label: 'Batalhão de Polícia de Meio Ambiente – BPMA', value: 'bpma' },
  { label: 'Regimento de Policia Montada – RPMONT', value: 'rpmont' },
  { label: 'Batalhão de Policiamento de Guarda Externa dos Presídios – BPGEP', value: 'bpgep' },
];
export const optionsDPGI: OptionType[] = [
  { label: 'DPGI - (Departamento de Polícia de Gestão Interna)', value: 'dpgi' },
  { label: 'CETIC - (Centro de Tecnologia da Informação e Comunicação)', value: 'cetic' },
  { label: 'CODIP - (Coordenadoria de Inteligência Policial)', value: 'codip' },
  { label: 'COLOG - (Coordenadoria de Logística)', value: 'colog' },
  { label: 'COAFI - (Coordenadoria de Assuntos Financeiros e Infraestrutura)', value: 'coafi' },
  { label: 'CGP - (Coordenação de Gestão de Pessoas)', value: 'cgp' },
  { label: 'CPMCE - (Comando de Policiamento do Meio-Centro Este)', value: 'cpmce' },
  { label: 'CSAS - (Coordenadoria de Segurança e Assuntos Sociais)', value: 'csas' },
  { label: 'COGEPRO - (Coordenadoria de Gestão e Processos)', value: 'cogepro' },
  { label: 'COGEI - (Coordenadoria de Gestão de Estatísticas e Informações)', value: 'cogei' },
];
export const optionsCPRAIO: OptionType[] = [
  { label: 'CPRAIO - (Comando de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: 'cpraio' },
  { label: '1º BPRAIO - (1º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '1bpraio' },
  { label: '2º BPRAIO - (2º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '2bpraio' },
  { label: '3º BPRAIO - (3º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '3bpraio' },
  { label: '4º BPRAIO - (4º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '4bpraio' },
  { label: '5º BPRAIO - (5º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '5bpraio' },
];
export const optionsEsp: OptionType[] = [
  { label: 'CPRAIO - (Comando de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: 'cpraio' },
  { label: '1º BPRAIO - (1º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '1bpraio' },
  { label: '2º BPRAIO - (2º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '2bpraio' },
  { label: '3º BPRAIO - (3º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '3bpraio' },
  { label: '4º BPRAIO - (4º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '4bpraio' },
  { label: '5º BPRAIO - (5º Batalhão de Policiamento de Rondas e Ações Intensivas e Ostensivas)', value: '5bpraio' },
  { label: 'Comando de Policiamento de Choque – CPCHOQUE', value: 'cpchoque' },
  { label: 'Batalhão de Comando Tático Motorizado – COTAM', value: 'cotam' },
  { label: 'Batalhão de Operações Policiais Especiais – BOPE', value: 'bope' },
  { label: 'Batalhão Especializado em Policiamento do Interior – BEPI', value: 'bepi' },
  { label: 'Batalhão de Polícia de Choque – BPCHOQUE', value: 'bpchoque' },
  { label: 'Batalhão de Polícia de Trânsito Urbano e Rodoviário Estadual – BPRE', value: 'bpre' },
  { label: 'Batalhão de Policiamento Turístico – BPTUR', value: 'bptur' },
  { label: 'Batalhão de Polícia de Meio Ambiente – BPMA', value: 'bpma' },
  { label: 'Regimento de Policia Montada – RPMONT', value: 'rpmont' },
  { label: 'Batalhão de Policiamento de Guarda Externa dos Presídios – BPGEP', value: 'bpgep' },
];
